In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])

In [3]:
arr1

array([1, 2, 3, 4, 5])

In [25]:
data = np.arange(100)

In [26]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [27]:
for i in range(len(data)):
    print(data[i], end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 

In [28]:
for i in range(len(data)):
    data[i] = data[i] + i

In [29]:
data

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198])

In [30]:
d1 = data[40:]

In [31]:
d1

array([ 80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198])

In [32]:
d2 = data[20:30]
d2

array([40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [33]:
d3 = data[30:50:5]

In [34]:
d3

array([60, 70, 80, 90])

In [35]:
d4 = data[30::5].copy()
d4

array([ 60,  70,  80,  90, 100, 110, 120, 130, 140, 150, 160, 170, 180,
       190])

In [36]:
data[30] = 1000

In [37]:
d4

array([ 60,  70,  80,  90, 100, 110, 120, 130, 140, 150, 160, 170, 180,
       190])

In [38]:
import copy
d_deep = copy.deepcopy(data)

In [39]:
d_deep

array([   0,    2,    4,    6,    8,   10,   12,   14,   16,   18,   20,
         22,   24,   26,   28,   30,   32,   34,   36,   38,   40,   42,
         44,   46,   48,   50,   52,   54,   56,   58, 1000,   62,   64,
         66,   68,   70,   72,   74,   76,   78,   80,   82,   84,   86,
         88,   90,   92,   94,   96,   98,  100,  102,  104,  106,  108,
        110,  112,  114,  116,  118,  120,  122,  124,  126,  128,  130,
        132,  134,  136,  138,  140,  142,  144,  146,  148,  150,  152,
        154,  156,  158,  160,  162,  164,  166,  168,  170,  172,  174,
        176,  178,  180,  182,  184,  186,  188,  190,  192,  194,  196,
        198])

In [40]:
for d in data:
    print(d, end=' ')

0 2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 1000 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98 100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180 182 184 186 188 190 192 194 196 198 

In [41]:
data = np.arange(100)

In [42]:
data[::3] = 0
data

array([ 0,  1,  2,  0,  4,  5,  0,  7,  8,  0, 10, 11,  0, 13, 14,  0, 16,
       17,  0, 19, 20,  0, 22, 23,  0, 25, 26,  0, 28, 29,  0, 31, 32,  0,
       34, 35,  0, 37, 38,  0, 40, 41,  0, 43, 44,  0, 46, 47,  0, 49, 50,
        0, 52, 53,  0, 55, 56,  0, 58, 59,  0, 61, 62,  0, 64, 65,  0, 67,
       68,  0, 70, 71,  0, 73, 74,  0, 76, 77,  0, 79, 80,  0, 82, 83,  0,
       85, 86,  0, 88, 89,  0, 91, 92,  0, 94, 95,  0, 97, 98,  0])

In [43]:
data.shape

(100,)

In [49]:
dr1 = data.reshape((4, 25))

In [50]:
dr1

array([[ 0,  1,  2,  0,  4,  5,  0,  7,  8,  0, 10, 11,  0, 13, 14,  0,
        16, 17,  0, 19, 20,  0, 22, 23,  0],
       [25, 26,  0, 28, 29,  0, 31, 32,  0, 34, 35,  0, 37, 38,  0, 40,
        41,  0, 43, 44,  0, 46, 47,  0, 49],
       [50,  0, 52, 53,  0, 55, 56,  0, 58, 59,  0, 61, 62,  0, 64, 65,
         0, 67, 68,  0, 70, 71,  0, 73, 74],
       [ 0, 76, 77,  0, 79, 80,  0, 82, 83,  0, 85, 86,  0, 88, 89,  0,
        91, 92,  0, 94, 95,  0, 97, 98,  0]])

In [51]:
data[::10] = 10000

In [52]:
dr1

array([[10000,     1,     2,     0,     4,     5,     0,     7,     8,
            0, 10000,    11,     0,    13,    14,     0,    16,    17,
            0,    19, 10000,     0,    22,    23,     0],
       [   25,    26,     0,    28,    29, 10000,    31,    32,     0,
           34,    35,     0,    37,    38,     0, 10000,    41,     0,
           43,    44,     0,    46,    47,     0,    49],
       [10000,     0,    52,    53,     0,    55,    56,     0,    58,
           59, 10000,    61,    62,     0,    64,    65,     0,    67,
           68,     0, 10000,    71,     0,    73,    74],
       [    0,    76,    77,     0,    79, 10000,     0,    82,    83,
            0,    85,    86,     0,    88,    89, 10000,    91,    92,
            0,    94,    95,     0,    97,    98,     0]])

In [55]:
dr1[3, 12] = -1000
dr1

array([[10000,     1,     2,     0,     4,     5,     0,     7,     8,
            0, 10000,    11,     0,    13,    14,     0,    16,    17,
            0,    19, 10000,     0,    22,    23,     0],
       [   25,    26,     0,    28,    29, 10000,    31,    32,     0,
           34,    35,     0,    37,    38,     0, 10000,    41,     0,
           43,    44,     0,    46,    47,     0,    49],
       [10000,     0,    52,    53,     0,    55,    56,     0,    58,
           59, 10000,    61,    62,     0,    64,    65,     0,    67,
           68,     0, 10000,    71,     0,    73,    74],
       [    0,    76,    77,     0,    79, 10000,     0,    82,    83,
            0,    85,    86, -1000,    88,    89, 10000,    91,    92,
            0,    94,    95,     0,    97,    98,     0]])

In [57]:
dr1[::2, ::4] = 20
dr1

array([[   20,     1,     2,     0,    20,     5,     0,     7,    20,
            0, 10000,    11,    20,    13,    14,     0,    20,    17,
            0,    19,    20,     0,    22,    23,    20],
       [   25,    26,     0,    28,    29, 10000,    31,    32,     0,
           34,    35,     0,    37,    38,     0, 10000,    41,     0,
           43,    44,     0,    46,    47,     0,    49],
       [   20,     0,    52,    53,    20,    55,    56,     0,    20,
           59, 10000,    61,    20,     0,    64,    65,    20,    67,
           68,     0,    20,    71,     0,    73,    20],
       [    0,    76,    77,     0,    79, 10000,     0,    82,    83,
            0,    85,    86, -1000,    88,    89, 10000,    91,    92,
            0,    94,    95,     0,    97,    98,     0]])

In [62]:
dr2 = data.reshape((1, 100))
dr2

array([[   20,     1,     2,     0,    20,     5,     0,     7,    20,
            0, 10000,    11,    20,    13,    14,     0,    20,    17,
            0,    19,    20,     0,    22,    23,    20,    25,    26,
            0,    28,    29, 10000,    31,    32,     0,    34,    35,
            0,    37,    38,     0, 10000,    41,     0,    43,    44,
            0,    46,    47,     0,    49,    20,     0,    52,    53,
           20,    55,    56,     0,    20,    59, 10000,    61,    20,
            0,    64,    65,    20,    67,    68,     0,    20,    71,
            0,    73,    20,     0,    76,    77,     0,    79, 10000,
            0,    82,    83,     0,    85,    86, -1000,    88,    89,
        10000,    91,    92,     0,    94,    95,     0,    97,    98,
            0]])

In [64]:
dr3 = data.reshape(100, 1)
dr3[:10]

array([[20],
       [ 1],
       [ 2],
       [ 0],
       [20],
       [ 5],
       [ 0],
       [ 7],
       [20],
       [ 0]])

In [65]:
data = np.arange(12)

In [66]:
m = data.reshape(3, 4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
data2 = np.arange(12)
m2 = data2.reshape(3, 4)
m2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
m * m2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [73]:
m + m2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [74]:
m - m2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [75]:
m ** m2

array([[           1,            1,            4,           27],
       [         256,         3125,        46656,       823543],
       [    16777216,    387420489,  10000000000, 285311670611]])

In [76]:
m3 = m2.reshape(4, 3)

In [78]:
np.matmul(m, m3)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [79]:
np.matmul(np.array([3, 5, 7, 1, 8, 2]).reshape(2, 3),
          np.array([3, 1, 8, 5, 1, 4]).reshape(3, 2))

array([[56, 56],
       [69, 49]])

In [80]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [87]:
np.zeros(10, dtype=str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [88]:
np.zeros(10, dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [89]:
np.zeros(10, dtype=np.int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [92]:
n = np.array([np.nan] * 10)

In [93]:
np.isnan(n[1])

True

In [95]:
rng = np.random.default_rng()

In [96]:
rng.integers(low=10, high=20, size=10)

array([16, 16, 15, 18, 18, 12, 10, 19, 11, 15])

In [100]:
rng.normal(loc=10, scale=2, size=10)

array([10.47875589, 11.33461248, 12.09773613,  8.36107372, 12.7816129 ,
       11.26107958, 10.71102056,  8.57667907, 10.64284559, 11.46066357])

In [102]:
rng.exponential(size=10)

array([0.27116061, 0.39537326, 0.23951622, 3.097945  , 0.67033323,
       0.25968795, 2.41001377, 3.65468436, 1.0163761 , 0.32412048])

In [105]:
np.histogram(rng.normal(loc=10, scale=2, size=10000))

(array([  15,  127,  706, 1924, 3051, 2561, 1237,  342,   32,    5]),
 array([ 2.42127707,  4.0142252 ,  5.60717334,  7.20012147,  8.7930696 ,
        10.38601773, 11.97896587, 13.571914  , 15.16486213, 16.75781027,
        18.3507584 ]))

In [106]:
np.histogram(rng.exponential(size=10000))

(array([6171, 2302,  921,  348,  173,   46,   21,   12,    3,    3]),
 array([3.53531152e-04, 9.48225011e-01, 1.89609649e+00, 2.84396797e+00,
        3.79183945e+00, 4.73971093e+00, 5.68758241e+00, 6.63545389e+00,
        7.58332537e+00, 8.53119685e+00, 9.47906833e+00]))

In [107]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [110]:
np.histogram(rng.uniform(size=10000))

(array([1014,  982, 1017, 1008, 1067,  991,  997, 1007,  973,  944]),
 array([5.55977106e-06, 1.00002827e-01, 2.00000095e-01, 2.99997362e-01,
        3.99994630e-01, 4.99991897e-01, 5.99989165e-01, 6.99986432e-01,
        7.99983699e-01, 8.99980967e-01, 9.99978234e-01]))